Repository sspanak/tt9, pull requests merged in 2022-11, with the labels that each got.

#101 Fixed an incorrect settings reset on startup
  src/io/github/sspanak/tt9/ime/TraditionalT9.java
Labels: bug

#98 Improved Candidate View
  res/drawable/suggestion_separator.xml
  res/layout/mainview.xml
  res/layout/suggestion_list_view.xml
  res/values/colors.xml
  res/values/dimens.xml
  src/io/github/sspanak/tt9/ime/KeyPadHandler.java
  src/io/github/sspanak/tt9/ime/SoftKeyHandler.java
  src/io/github/sspanak/tt9/ime/TraditionalT9.java
  src/io/github/sspanak/tt9/preferences/T9Preferences.java
  src/io/github/sspanak/tt9/ui/CandidateView.java
  src/io/github/sspanak/tt9/ui/SuggestionsAdapter.java
  src/io/github/sspanak/tt9/ui/SuggestionsView.java
Labels: bug

#100 Dictionary import progress is now displayed as a standard Android notification
  res/drawable-anydpi-v24/ic_notification.xml
  res/drawable-hdpi/ic_notification.png
  res/drawable-mdpi/ic_notification.png
  res/drawable-xhdpi/ic_notification.png
  res/drawable-xxhdpi/ic_notification.png
  res/values-bg/strings.xml
  res/values-fr/strings.xml
  res/values-it/strings.xml
  res/values-nl/strings.xml
  res/values-ru/strings.xml
  res/values-uk/strings.xml
  res/values/strings.xml
  src/io/github/sspanak/tt9/db/DictionaryImportAlreadyRunningException.java
  src/io/github/sspanak/tt9/db/DictionaryLoader.java
  src/io/github/sspanak/tt9/preferences/T9Preferences.java
  src/io/github/sspanak/tt9/ui/DictionaryLoadingBar.java
  src/io/github/sspanak/tt9/ui/TraditionalT9Settings.java
Labels: enhancement

#106 upgrade gradle to 7.3.1
  build.gradle
Labels: technical

#105 Random bugs again
  res/layout/mainview.xml
  res/values/dimens.xml
  src/io/github/sspanak/tt9/ime/TraditionalT9.java
  src/io/github/sspanak/tt9/ime/modes/ModeABC.java
Labels: bug

#109 Improved dictionary loading status
  res/drawable-anydpi-v24/ic_done.xml
  res/drawable-anydpi-v24/ic_notification.xml
  res/drawable-hdpi/ic_done.png
  res/drawable-hdpi/ic_notification.png
  res/drawable-mdpi/ic_done.png
  res/drawable-mdpi/ic_notification.png
  res/drawable-xhdpi/ic_done.png
  res/drawable-xhdpi/ic_notification.png
  res/drawable-xxhdpi/ic_done.png
  res/drawable-xxhdpi/ic_notification.png
  res/layout/mainview.xml
  res/values-bg/strings.xml
  res/values-fr/strings.xml
  res/values-it/strings.xml
  res/values-ru/strings.xml
  res/values-uk/strings.xml
  res/values/strings.xml
  src/io/github/sspanak/tt9/ui/DictionaryLoadingBar.java
  src/io/github/sspanak/tt9/ui/TraditionalT9Settings.java
Labels: bug

#110 Fixed crashing when trying to add a new word but the input connection is closed
  src/io/github/sspanak/tt9/ime/InputFieldHelper.java
  src/io/github/sspanak/tt9/ime/TraditionalT9.java
Labels: bug

#121 Improved version name generator
  build.gradle
Labels: technical

#120 Update README.md
  README.md
Labels: technical
