Repository sspanak/tt9, pull requests merged in 2023-05, with the labels that each got.

#250 Speed optimizations
  src/io/github/sspanak/tt9/ConsumerCompat.java
  src/io/github/sspanak/tt9/Logger.java
  src/io/github/sspanak/tt9/db/DictionaryDb.java
  src/io/github/sspanak/tt9/db/DictionaryLoader.java
  src/io/github/sspanak/tt9/db/migrations/DB8.java
  src/io/github/sspanak/tt9/db/migrations/DB9.java
  src/io/github/sspanak/tt9/db/room/TT9Room.java
  src/io/github/sspanak/tt9/db/room/Word.java
  src/io/github/sspanak/tt9/db/room/WordList.java
  src/io/github/sspanak/tt9/db/room/WordsDao.java
  src/io/github/sspanak/tt9/ime/EmptyDatabaseWarning.java
  src/io/github/sspanak/tt9/ime/TraditionalT9.java
  src/io/github/sspanak/tt9/ime/modes/InputMode.java
  src/io/github/sspanak/tt9/ime/modes/ModePredictive.java
  src/io/github/sspanak/tt9/ime/modes/helpers/Predictions.java
  src/io/github/sspanak/tt9/languages/Characters.java
  src/io/github/sspanak/tt9/preferences/items/ItemLoadDictionary.java
  src/io/github/sspanak/tt9/preferences/items/ItemTruncateAll.java
  src/io/github/sspanak/tt9/preferences/items/ItemTruncateUnselected.java
  src/io/github/sspanak/tt9/ui/AddWordAct.java
  src/io/github/sspanak/tt9/ui/UI.java
Labels: enhancement

#258 Fixed unusable hotkeys and typing issues in very specific cases
  src/io/github/sspanak/tt9/ime/KeyPadHandler.java
  src/io/github/sspanak/tt9/ime/TraditionalT9.java
  src/io/github/sspanak/tt9/ime/helpers/InputType.java
  src/io/github/sspanak/tt9/ime/helpers/Key.java
  src/io/github/sspanak/tt9/ime/helpers/TextField.java
  src/io/github/sspanak/tt9/ime/modes/InputMode.java
  src/io/github/sspanak/tt9/ime/modes/Mode123.java
  src/io/github/sspanak/tt9/ime/modes/ModeABC.java
  src/io/github/sspanak/tt9/ime/modes/ModeDialer.java
  src/io/github/sspanak/tt9/ime/modes/ModePredictive.java
  src/io/github/sspanak/tt9/preferences/helpers/Hotkeys.java
  src/io/github/sspanak/tt9/ui/main/keys/SoftPunctuationKey.java
Labels: bug

#248 Add Indonesian language
  assets/id-utf8.csv
  docs/dictionaries/idWordlistReadme.txt
  src/io/github/sspanak/tt9/languages/LanguageCollection.java
  src/io/github/sspanak/tt9/languages/definitions/Indonesian.java
Labels: languages

#247 Add Yiddish Language
  assets/ji-utf8.csv
  docs/dictionaries/jiWordlistReadme.txt
  src/io/github/sspanak/tt9/languages/LanguageCollection.java
  src/io/github/sspanak/tt9/languages/definitions/Yiddish.java
Labels: languages

#270 upgrade Gradle 8.0.1 -> 8.0.2
  build.gradle
Labels: technical

#265 mEditing is no more
  src/io/github/sspanak/tt9/ime/TraditionalT9.java
  src/io/github/sspanak/tt9/ime/helpers/InputModeValidator.java
  src/io/github/sspanak/tt9/ime/modes/InputMode.java
  src/io/github/sspanak/tt9/preferences/PreferencesActivity.java
  src/io/github/sspanak/tt9/ui/main/keys/SoftNumberKey.java
  src/io/github/sspanak/tt9/ui/main/keys/SoftPunctuationKey.java
  src/io/github/sspanak/tt9/ui/tray/StatusBar.java
Labels: bug, technical
