Repository sspanak/tt9, pull requests merged in 2023-03, with the labels that each got.

#209 Added support for Clear key
  res/values/strings.xml
  src/io/github/sspanak/tt9/preferences/helpers/Hotkeys.java
  src/io/github/sspanak/tt9/preferences/items/SectionKeymap.java
Labels: enhancement

#191 Norwegian
  assets/nb-utf8.csv
  docs/dictionaries/nbWordListReadme.txt
  res/drawable-anydpi-v24/ime_lang_nb.xml
  res/drawable-hdpi/ime_lang_nb.png
  res/drawable-mdpi/ime_lang_nb.png
  res/drawable-xhdpi/ime_lang_nb.png
  res/drawable-xxhdpi/ime_lang_nb.png
  src/io/github/sspanak/tt9/languages/LanguageCollection.java
  src/io/github/sspanak/tt9/languages/definitions/Norwegian.java
Labels: languages

#211 Punctuation improvements
  src/io/github/sspanak/tt9/ime/TraditionalT9.java
  src/io/github/sspanak/tt9/ime/helpers/TextField.java
  src/io/github/sspanak/tt9/ime/modes/InputMode.java
  src/io/github/sspanak/tt9/ime/modes/ModePredictive.java
  src/io/github/sspanak/tt9/ime/modes/helpers/AutoSpace.java
  src/io/github/sspanak/tt9/ime/modes/helpers/AutoTextCase.java
  src/io/github/sspanak/tt9/ime/modes/helpers/Predictions.java
Labels: enhancement, technical

#217 Add soft key support
  res/values/strings.xml
  src/io/github/sspanak/tt9/preferences/helpers/Hotkeys.java
Labels: enhancement

#220 Add Finnish language
  assets/fi-utf8.csv
  docs/dictionaries/fiWordlistReadme.txt
  res/drawable-anydpi-v24/ime_lang_fi.xml
  res/drawable-hdpi/ime_lang_fi.png
  res/drawable-mdpi/ime_lang_fi.png
  res/drawable-xhdpi/ime_lang_fi.png
  res/drawable-xxhdpi/ime_lang_fi.png
  src/io/github/sspanak/tt9/languages/LanguageCollection.java
  src/io/github/sspanak/tt9/languages/definitions/Finnish.java
Labels: languages

#223 Swedish language
  assets/sv-utf8.csv
  docs/dictionaries/svWordListReadme.txt
  res/drawable-anydpi-v24/ime_lang_sv.xml
  res/drawable-hdpi/ime_lang_sv.png
  res/drawable-mdpi/ime_lang_sv.png
  res/drawable-xhdpi/ime_lang_sv.png
  res/drawable-xxhdpi/ime_lang_sv.png
  src/io/github/sspanak/tt9/languages/LanguageCollection.java
  src/io/github/sspanak/tt9/languages/definitions/Swedish.java
Labels: languages

#224 fixed dialer field detection (without breaking Contacts)
  src/io/github/sspanak/tt9/ime/helpers/InputType.java
Labels: bug

#233 Easier access to the setup screen
  res/values-bg/strings.xml
  res/values-fr/strings.xml
  res/values-ru/strings.xml
  res/values-uk/strings.xml
  res/values/strings.xml
  res/xml/prefs.xml
  res/xml/prefs_screen_setup.xml
  src/io/github/sspanak/tt9/preferences/PreferencesActivity.java
  src/io/github/sspanak/tt9/preferences/screens/MainSettingsScreen.java
  src/io/github/sspanak/tt9/preferences/screens/SetupScreen.java
Labels: enhancement
