Repository sspanak/tt9, pull requests merged in 2024-09, with the labels that each got.

#615 the WordStore is now explicitly destroyed on shutdown
  app/src/main/java/io/github/sspanak/tt9/db/WordStore.java
  app/src/main/java/io/github/sspanak/tt9/db/WordStoreAsync.java
  app/src/main/java/io/github/sspanak/tt9/ime/TraditionalT9.java
Labels: bug

#617 fixed crashing when pressing OK in the language search field
  app/src/main/java/io/github/sspanak/tt9/preferences/screens/languageSelection/PreferenceSearchLanguage.java
Labels: bug

#618 fixed suggestion selection getting reset when toggling the text case
  app/src/main/java/io/github/sspanak/tt9/ime/CommandHandler.java
  app/src/main/java/io/github/sspanak/tt9/ime/helpers/SuggestionOps.java
  app/src/main/java/io/github/sspanak/tt9/ui/tray/SuggestionsBar.java
Labels: bug

#620 fixed language search crashing for real this time
  app/src/main/java/io/github/sspanak/tt9/preferences/items/ItemTextInput.java
  app/src/main/java/io/github/sspanak/tt9/preferences/screens/languageSelection/PreferenceSearchLanguage.java
  app/src/main/res/layout/pref_input_text.xml
Labels: bug

#616 Word pair predicitions
  app/src/main/java/io/github/sspanak/tt9/db/DataStore.java
  app/src/main/java/io/github/sspanak/tt9/db/sqlite/DeleteOps.java
  app/src/main/java/io/github/sspanak/tt9/db/sqlite/InsertOps.java
  app/src/main/java/io/github/sspanak/tt9/db/sqlite/ReadOps.java
  app/src/main/java/io/github/sspanak/tt9/db/sqlite/SQLiteOpener.java
  app/src/main/java/io/github/sspanak/tt9/db/sqlite/Tables.java
  app/src/main/java/io/github/sspanak/tt9/db/wordPairs/WordPair.java
  app/src/main/java/io/github/sspanak/tt9/db/wordPairs/WordPairStore.java
  app/src/main/java/io/github/sspanak/tt9/db/words/DictionaryLoader.java
  app/src/main/java/io/github/sspanak/tt9/db/words/LegacyDb.java
  app/src/main/java/io/github/sspanak/tt9/db/words/SlowQueryStats.java
  app/src/main/java/io/github/sspanak/tt9/db/words/WordStore.java
  app/src/main/java/io/github/sspanak/tt9/ime/CommandHandler.java
  app/src/main/java/io/github/sspanak/tt9/ime/HotkeyHandler.java
  app/src/main/java/io/github/sspanak/tt9/ime/TraditionalT9.java
  app/src/main/java/io/github/sspanak/tt9/ime/TypingHandler.java
  app/src/main/java/io/github/sspanak/tt9/ime/helpers/TextField.java
  app/src/main/java/io/github/sspanak/tt9/ime/modes/InputMode.java
  app/src/main/java/io/github/sspanak/tt9/ime/modes/ModePredictive.java
  app/src/main/java/io/github/sspanak/tt9/ime/modes/helpers/Predictions.java
  app/src/main/java/io/github/sspanak/tt9/preferences/PreferencesActivity.java
  app/src/main/java/io/github/sspanak/tt9/preferences/screens/UsageStatsScreen.java
  app/src/main/java/io/github/sspanak/tt9/preferences/screens/deleteWords/PreferenceDeletableWord.java
  app/src/main/java/io/github/sspanak/tt9/preferences/screens/deleteWords/PreferenceSearchWords.java
  app/src/main/java/io/github/sspanak/tt9/preferences/screens/languageSelection/LanguageSelectionScreen.java
  app/src/main/java/io/github/sspanak/tt9/preferences/screens/languages/ItemLoadDictionary.java
  app/src/main/java/io/github/sspanak/tt9/preferences/screens/languages/ItemTruncateAll.java
  app/src/main/java/io/github/sspanak/tt9/preferences/screens/languages/ItemTruncateUnselected.java
  app/src/main/java/io/github/sspanak/tt9/preferences/screens/languages/LanguagesScreen.java
  app/src/main/java/io/github/sspanak/tt9/preferences/settings/SettingsStore.java
  app/src/main/java/io/github/sspanak/tt9/preferences/settings/SettingsTyping.java
  app/src/main/java/io/github/sspanak/tt9/ui/dialogs/AddWordDialog.java
  app/src/main/java/io/github/sspanak/tt9/ui/dialogs/AutoUpdateMonologue.java
  app/src/main/java/io/github/sspanak/tt9/util/Text.java
  app/src/main/res/xml/prefs_screen_usage_stats.xml
Labels: enhancement

#627 Zombie checks at startup
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/sspanak/tt9/ime/TraditionalT9.java
Labels: bug

#629 Add Thai language support
  CONTRIBUTING.md
  app/languages/definitions/Thai.yml
  app/languages/dictionaries/th-utf8.csv
  app/src/main/java/io/github/sspanak/tt9/ime/modes/ModePredictive.java
  app/src/main/java/io/github/sspanak/tt9/ime/modes/helpers/AutoSpace.java
  app/src/main/java/io/github/sspanak/tt9/languages/Language.java
  app/src/main/java/io/github/sspanak/tt9/languages/LanguageDefinition.java
  app/src/main/java/io/github/sspanak/tt9/languages/LanguageKind.java
  app/src/main/java/io/github/sspanak/tt9/languages/NaturalLanguage.java
  app/src/main/java/io/github/sspanak/tt9/preferences/settings/SettingsStore.java
  app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftKeyNumber.java
  app/src/main/java/io/github/sspanak/tt9/util/TextTools.java
  app/validate-languages.gradle
  docs/dictionaries/thWordlistReadme.txt
  fastlane/metadata/android/bg-BG/full_description.txt
  fastlane/metadata/android/en-US/full_description.txt
Labels: languages

#633 added a button to disable the system spell checker
  app/src/main/java/io/github/sspanak/tt9/preferences/screens/setup/ItemSpellCheck.java
  app/src/main/java/io/github/sspanak/tt9/preferences/screens/setup/SetupScreen.java
  app/src/main/java/io/github/sspanak/tt9/ui/UI.java
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/prefs_screen_setup.xml
  docs/user-manual.md
Labels: enhancement

#638 LF4 icon fine tuning
  app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftKey.java
  app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftKeyLF4.java
Labels: enhancement
